version: '3.9'
services:
  db:
    image: postgres:16
    container_name: nestjs_test_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: nestjs_test_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: nestjs_app
  #   restart: unless-stopped
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
volumes:
  db_data:
